from facebook.views.register_user_view import RegisterUserView
from facebook.views.login_user_view import LoginUserView
from facebook.views.user_list_view import UserListView
from facebook.views.user_friend_list_view import UserFriendListView
from facebook.views.send_friend_request_view import SendFriendRequestView
from facebook.views.accept_friend_request_view import AcceptFriendRequestView
from facebook.views.reject_friend_request_view import RejectFriendRequestView
from facebook.views.pending_friend_request_list_view import PendingFriendRequestListView
